{{- range $key, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "atlas.labels" (dict "service" $svc) | nindent 4 }}
  {{- if $svc.serviceAccountRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $svc.serviceAccountRoleArn }}
  {{- end }}
---
{{- end }}
